#Gives permission to install Salesforce CLI
sudo: true

before_install:
#
# The before_install steps downloads Salesforce CLI and installs it
#

#Decrypt server key
#- openssl aes-256-cbc -K $encrypted_b105d3438aa4_key -iv $encrypted_b105d3438aa4_iv
#  -in assets/server.key.enc -out assets/server.key -d
#Assign variables
- export CLIURL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz  
- export SFDX_AUTOUPDATE_DISABLE=false
- export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
- export SFDX_DOMAIN_RETRY=300
- export SFDX_DISABLE_APP_HUB=true
- export SFDX_LOG_LEVEL=DEBUG
#Create SFDX directory
- mkdir sfdx
#Install Salesforce CLI
- wget -qO- $CLIURL | tar xJ -C sfdx --strip-components 1
- ./sfdx/install
- export PATH=./sfdx/$(pwd):$PATH

before_script:
#
# The before_script step initializes variables used in the script step and authenticates to the Dev Hub using the JWT-based flow
#

#Assign variables
- export ROOTDIR=force-app/main/default/
- export TESTLEVEL=RunLocalTests
#Be sure to update the package ID (package ID starts with OHo) or package alias here from the sfdx-project.json file
- export PACKAGENAME="0Ho0N000000CaT3SAK"
- export PACKAGEVERSION=""

script:
#outputs CLI version
- sfdx --version
#outputs salsforcedx plugin version
- sfdx plugins --core
